#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerCommitments.Web.Views.EmployerManageApprentices
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.EmployerCommitments;
    using SFA.DAS.EmployerCommitments.Web.ViewModels;
    using SFA.DAS.EmployerCommitments.Web.ViewModels.ManageApprenticeships;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmployerManageApprentices/ConfirmChanges.cshtml")]
    public partial class ConfirmChanges : System.Web.Mvc.WebViewPage<SFA.DAS.EmployerCommitments.Web.OrchestratorResponse<UpdateApprenticeshipViewModel>>
    {
        public ConfirmChanges()
        {
        }
        public override void Execute()
        {
  
    ViewBag.Title = "Confirm changes";
    ViewBag.Section = "apprentices";
    ViewBag.PageID = "confirm-edited-changes";

    Model.Data.CurrentTableHeadingText = "Current";

    var learnerName = $"{Model.Data?.OriginalApprenticeship?.FirstName} {Model.Data?.OriginalApprenticeship?.LastName}";
    var uln = Model.Data?.OriginalApprenticeship?.ULN;
    var trainingName = Model.Data?.OriginalApprenticeship?.TrainingName;

WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-full\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" method=\"POST\"");

WriteAttribute("action", Tuple.Create(" action=\"", 742), Tuple.Create("\"", 779)
, Tuple.Create(Tuple.Create("", 751), Tuple.Create<System.Object, System.Int32>(Url.Action("SubmitChanges")
, 751), false)
);

WriteLiteral(" novalidate=\"novalidate\"");

WriteAttribute("onsubmit", Tuple.Create(" onsubmit=\"", 804), Tuple.Create("\"", 862)
, Tuple.Create(Tuple.Create("", 815), Tuple.Create("sfa.tagHelper.submitRadioForm(\'", 815), true)
                                                    , Tuple.Create(Tuple.Create("", 846), Tuple.Create<System.Object, System.Int32>(ViewBag.Title
, 846), false)
, Tuple.Create(Tuple.Create("", 860), Tuple.Create("\')", 860), true)
);

WriteLiteral(">\r\n            \r\n");

WriteLiteral("            ");

       Write(Html.AntiForgeryToken());

WriteLiteral("\r\n\r\n            <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">");

                                  Write(ViewBag.Title);

WriteLiteral("</h1>\r\n            \r\n");

            
               Html.RenderPartial("_CoreDetail", new CoreDetailsViewModel
               {
                   LearnerName = learnerName,
                   ULN = uln,
                   TrainingName = trainingName
               }); 
WriteLiteral("\r\n            \r\n");

            
               Html.RenderPartial("ApprenticeshipUpdate", Model.Data); 
WriteLiteral("\r\n                <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Do you want to make these changes?</h2>\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1427), Tuple.Create("\"", 1519)
, Tuple.Create(Tuple.Create("", 1435), Tuple.Create("form-group", 1435), true)
, Tuple.Create(Tuple.Create(" ", 1445), Tuple.Create<System.Object, System.Int32>(!string.IsNullOrEmpty(Model.Data.ChangesConfirmedError) ? "error" : ""
, 1446), false)
);

WriteLiteral(">\r\n                    <fieldset>\r\n                        <legend");

WriteLiteral(" class=\"visually-hidden\"");

WriteLiteral(">Do you want to make these changes?</legend>\r\n            \r\n                     " +
"   <div");

WriteLiteral(" id=\"ChangesConfirmed\"");

WriteLiteral("></div>\r\n");

                        
                         if (!string.IsNullOrEmpty(Model.Data.ChangesConfirmedError))
                        {

WriteLiteral("                            <span");

WriteLiteral(" class=\"error-message\"");

WriteLiteral(" id=\"error-message-ChangesConfirmed\"");

WriteLiteral(">");

                                                                                       Write(Model.Data.ChangesConfirmedError);

WriteLiteral("</span>\r\n");

                        }

WriteLiteral("\r\n                        <label");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(" for=\"changes-confirmed-true\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

                       Write(Html.RadioButton("ChangesConfirmed", true, new { id = "changes-confirmed-true", dataOptionName = "Yes", onclick = $"sfa.tagHelper.radioButtonClick('{ViewBag.Title}', 'Yes')" }));

WriteLiteral("\r\n                            Yes, change these details\r\n                        " +
"</label>\r\n                        <label");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(" for=\"changes-confirmed-false\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

                       Write(Html.RadioButton("ChangesConfirmed", false, new { id = "changes-confirmed-false", dataOptionName = "No", onclick = $"sfa.tagHelper.radioButtonClick('{ViewBag.Title}', 'No')" }));

WriteLiteral("\r\n                            No, don\'t change these details\r\n                   " +
"     </label>\r\n                    </fieldset>\r\n                </div>\r\n\r\n      " +
"          <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(" aria-label=\"Finish\"");

WriteLiteral(" id=\"submit-confirm-change\"");

WriteLiteral(">Finish</button>\r\n        </form>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("breadcrumb", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3093), Tuple.Create("\"", 3151)
, Tuple.Create(Tuple.Create("", 3100), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", "EmployerManageApprentices")
, 3100), false)
);

WriteLiteral(" aria-label=\"Back to apprentice details\"");

WriteLiteral(" class=\"back-link\"");

WriteLiteral(">Back to apprentice details</a>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

DefineSection("gaDataLayer", () => {

WriteLiteral("\r\n    <script>\r\n        sfa.dataLayer.vpv = \'/accounts/apprentices/manage/confirm" +
"-edited-changes\';\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
