#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerCommitments.Web.Views.EmployerManageApprentices
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.Commitments.Api.Types.Apprenticeship.Types;
    using SFA.DAS.EmployerCommitments;
    using SFA.DAS.EmployerCommitments.Web.Extensions;
    using SFA.DAS.EmployerCommitments.Web.ViewModels.ManageApprenticeships;
    using SFA.DAS.EmployerUrlHelper;
    using SFA.DAS.EmployerUrlHelper.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmployerManageApprentices/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<SFA.DAS.EmployerCommitments.Web.OrchestratorResponse<ApprenticeshipDetailsViewModel>>
    {
            
    public string FormatCost(decimal? cost)
    {
        if (!cost.HasValue)
            return string.Empty;

        return $"£{cost.Value:n0}";
    }

        public Details()
        {
        }
        public override void Execute()
        {
  
    ViewBag.Title = "Apprentice detail";
    ViewBag.Section = "apprentices";
    ViewBag.PageId = "apprentices-detail";

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n\r\n");

        
         if (Model.Data.PendingChanges == PendingChanges.ReadyForApproval)
        {

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-border-wide alert-default\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Changes for review</h3>\r\n                <p>\r\n                    The training p" +
"rovider has made a change which needs to be reviewed and approved by the employe" +
"r;\r\n                </p>\r\n                <p>\r\n                    <a");

WriteLiteral(" id=\"review-changes-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 954), Tuple.Create("\"", 991)
, Tuple.Create(Tuple.Create("", 961), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl("ReviewChanges")
, 961), false)
);

WriteLiteral(">Review changes</a>\r\n                </p>\r\n            </div>\r\n");

        }
        else if (Model.Data.PendingChanges == PendingChanges.WaitingForApproval)
        {

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-border-wide\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Changes pending</h3>\r\n                <p>\r\n                    The employer has " +
"made a change which needs to be approved by the training provider\r\n             " +
"   <p>\r\n                    <a");

WriteLiteral(" id=\"view-changes-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1465), Tuple.Create("\"", 1529)
, Tuple.Create(Tuple.Create("", 1472), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl("ViewChanges", "EmployerManageApprentices")
, 1472), false)
);

WriteLiteral(">View changes</a>\r\n                </p>\r\n            </div>\r\n");

        }

WriteLiteral("\r\n");

        
         if (Model.Data.HasPendingChangeOfProviderRequest
            && Model.Data.PendingChangeOfProviderRequestWithParty.HasValue)
        {

WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-border-wide alert-default\"");

WriteLiteral(">\r\n");

        
         if (Model.Data.PendingChangeOfProviderRequestWithParty.Value == Party.Employer)
        {

WriteLiteral("            <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Changes for review</h3>\r\n");

WriteLiteral("            <p>\r\n                There are changes to this apprentice\'s details t" +
"hat you need to review.\r\n            </p>\r\n");

WriteLiteral("            <p>\r\n                <a");

WriteLiteral(" id=\"changeOfPartyViewChangesLink\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2165), Tuple.Create("\"", 2199)
, Tuple.Create(Tuple.Create("", 2172), Tuple.Create<System.Object, System.Int32>(Model.Data.ViewChangesLink
, 2172), false)
);

WriteLiteral(">Review changes</a>\r\n            </p>\r\n");

        }
        else
        {

WriteLiteral("            <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Changes pending</h3>\r\n");

WriteLiteral("            <p>\r\n                There are changes to this apprentice\'s details t" +
"hat are waiting for approval by the training provider.\r\n            </p>\r\n");

WriteLiteral("            <p>\r\n                <a");

WriteLiteral(" id=\"changeOfPartyViewChangesLink\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2559), Tuple.Create("\"", 2593)
, Tuple.Create(Tuple.Create("", 2566), Tuple.Create<System.Object, System.Int32>(Model.Data.ViewChangesLink
, 2566), false)
);

WriteLiteral(">View changes</a>\r\n            </p>\r\n");

        }

WriteLiteral("\r\n    </div>\r\n");

        }

WriteLiteral("\r\n\r\n");

        
         if (Model.Data.HasApprovedChangeOfProviderRequest || Model.Data.IsContinuation)
        {


WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-border-wide alert-default\"");

WriteLiteral(">\r\n\r\n\r\n");

                
                 if (Model.Data.HasApprovedChangeOfProviderRequest && Model.Data.IsContinuation)
                {

WriteLiteral("                    <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">  View apprentice record </h3>\r\n");

WriteLiteral("                    <p>\r\n                        The apprentice moved providers d" +
"uring their apprenticeship.\r\n                    </p>\r\n");

                }
                else if (Model.Data.HasApprovedChangeOfProviderRequest)
                {

WriteLiteral("                    <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">  View apprentice record </h3>\r\n");

WriteLiteral("                    <p>\r\n                        The apprentice moved providers d" +
"uring their apprenticeship.\r\n                    </p>\r\n");

                }
                else if (Model.Data.IsContinuation)
                {

WriteLiteral("                    <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">  View apprentice record </h3>\r\n");

WriteLiteral("                    <p>\r\n                        The apprentice moved providers d" +
"uring their apprenticeship.\r\n                    </p>\r\n");

                }

WriteLiteral("\r\n\r\n");

                
                 if (!string.IsNullOrWhiteSpace(Model.Data.HashedNewApprenticeshipId))
                {

WriteLiteral("                    <p>\r\n                        <a");

WriteLiteral(" id=\"continuation-link\"");

WriteLiteral(" class=\"govuk-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4018), Tuple.Create("\"", 4118)
, Tuple.Create(Tuple.Create("", 4025), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", new { hashedApprenticeshipId = Model.Data.HashedNewApprenticeshipId })
, 4025), false)
);

WriteLiteral(">View the new apprentice record</a>\r\n                    </p>\r\n");

                }

WriteLiteral("\r\n");

                
                 if (!string.IsNullOrWhiteSpace(Model.Data.HashedPreviousApprenticeshipId))
                {

WriteLiteral("                    <p>\r\n                        <a");

WriteLiteral(" id=\"previous-apprentice-link\"");

WriteLiteral(" class=\"govuk-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4415), Tuple.Create("\"", 4520)
  , Tuple.Create(Tuple.Create("", 4422), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", new { hashedApprenticeshipId = Model.Data.HashedPreviousApprenticeshipId })
, 4422), false)
);

WriteLiteral(">View the old apprentice record</a>\r\n                    </p>\r\n");

                }

WriteLiteral("            </div>\r\n");

        }

WriteLiteral("\r\n");

        
         if (Model.Data.PendingDataLockRestart)
        {

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-border-wide\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(@">
                    Changes requested
                </h3>
                <p>
                    The apprentice's training provider has asked you to stop this apprentice
                    and then add them to a new cohort using updated training details.
                </p>
                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5095), Tuple.Create("\"", 5133)
, Tuple.Create(Tuple.Create("", 5102), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl("RequestRestart")
, 5102), false)
);

WriteLiteral(" aria-label=\"View details\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">View details</a>\r\n            </div>\r\n");

        }

WriteLiteral("        ");

         if (Model.Data.PendingDataLockChange)
        {

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-border-wide\"");

WriteLiteral(">\r\n                <h3>\r\n                    Changes for review\r\n                " +
"</h3>\r\n                <p>\r\n                    There are changes to this appren" +
"tice\'s details that you need to review.\r\n                </p>\r\n                <" +
"a");

WriteAttribute("href", Tuple.Create(" href=\"", 5568), Tuple.Create("\"", 5606)
, Tuple.Create(Tuple.Create("", 5575), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl("RequestChanges")
, 5575), false)
);

WriteLiteral(" aria-label=\"View details\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">Review changes</a>\r\n            </div>\r\n");

        }

WriteLiteral("\r\n        <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(" id=\"learnerName\"");

WriteLiteral(">");

                                               Write(Model.Data.FirstName);

WriteLiteral(" ");

                                                                     Write(Model.Data.LastName);

WriteLiteral("</h1>\r\n\r\n");

        
           if (!Model.Data.Status.Equals("Stopped", StringComparison.InvariantCultureIgnoreCase) &&
                     Model.Data.PaymentStatus != PaymentStatus.Completed)
            {

WriteLiteral("                <p>\r\n                    Edit details if there\'s a change in appr" +
"entice or apprenticeship circumstances.\r\n                </p>\r\n");

            }
        
WriteLiteral("\r\n\r\n        <h2");

WriteLiteral(" class=\"heading-medium visually-hidden\"");

WriteLiteral(">Apprentice status</h2>\r\n        <table");

WriteLiteral(" id=\"app-status\"");

WriteLiteral(" class=\"details-list details-list-new\"");

WriteLiteral(">\r\n            <tbody>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Status</th>\r\n                    <td>");

                   Write(Model.Data.Status);

WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" id=\"editStatusLink\"");

WriteLiteral(" class=\"link-right\"");

WriteLiteral(">\r\n");

                        
                         if (Model.Data.CanEditStatus)
                        {
                            
                       Write(Html.RouteLink("Edit status", "ChangeStatusSelectOption"));

                                                                                      ;
                        }

WriteLiteral("                    </td>\r\n                </tr>\r\n");

                
                 if (@Model.Data.PaymentStatus == PaymentStatus.Paused)
                {

WriteLiteral("                    <tr>\r\n                        <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Apprenticeship pause date</th>\r\n                        <td");

WriteLiteral(" id=\"pauseDate\"");

WriteLiteral(">\r\n");

                            
                             if (Model.Data.PauseDate.HasValue)
                            {
                                
                           Write(Model.Data.PauseDate.Value.ToGdsFormat());

                                                                         
                            }

WriteLiteral("                        </td>\r\n                        <td></td>\r\n               " +
"     </tr>\r\n");

                }

WriteLiteral("\r\n");

                
                 if (@Model.Data.PaymentStatus == PaymentStatus.Completed)
                {

WriteLiteral("                    <tr>\r\n                        <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Completion payment month</th>\r\n                        <td");

WriteLiteral(" id=\"completionDate\"");

WriteLiteral(">\r\n");

                            
                             if (Model.Data.CompletionDate.HasValue)
                            {
                                
                           Write(Model.Data.CompletionDate.Value.ToGdsFormatLongMonthNameWithoutDay());

                                                                                                     ;
                            }

WriteLiteral("                        </td>\r\n                        <td></td>\r\n               " +
"     </tr>\r\n");

                }

WriteLiteral("\r\n\r\n");

                
                 if (Model.Data.PaymentStatus == PaymentStatus.Withdrawn)
                {

WriteLiteral("                    <tr>\r\n                        <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Stopped date</th>\r\n                        <td");

WriteLiteral(" id=\"stopDate\"");

WriteLiteral(">\r\n");

                            
                             if (Model.Data.StopDate.HasValue)
                            {
                                
                           Write(Model.Data.StopDate.Value.ToGdsFormatWithoutDay());

                                                                                  
                            }

WriteLiteral("                        </td>\r\n\r\n");

                        
                         if (Model.Data.CanEditStopDate)
                        {

WriteLiteral("                            <td");

WriteLiteral(" id=\"editStopDateLink\"");

WriteLiteral(" class=\"link-right\"");

WriteLiteral(">");

                                                                    Write(Html.RouteLink("Edit", "EditStopDateOption"));

WriteLiteral("</td>\r\n");

                        }
                        else
                        {

WriteLiteral("                            <td></td>\r\n");

                        }

WriteLiteral("                    </tr>\r\n");


                    if (Model.Data.MadeRedundant.HasValue)
                    {

WriteLiteral("                        <tr>\r\n                            <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Made redundant</th>\r\n                            <td");

WriteLiteral(" id=\"madeRedundant\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

                            Write(Model.Data.MadeRedundant.Value ? "Yes" : "No");

WriteLiteral("\r\n                            </td>\r\n                            <td></td>\r\n     " +
"                   </tr>\r\n");

                    }
                }

WriteLiteral("                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Training provider</th>\r\n                    <td>");

                   Write(Model.Data.ProviderName);

WriteLiteral("</td>\r\n");

                    
                     if (Model.Data.ShowChangeTrainingProviderLink)
                    {

WriteLiteral("                        <td");

WriteLiteral(" class=\"link-right\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" id=\"changeTrainingProviderLink\"");

WriteAttribute("href", Tuple.Create(" href=\"", 9561), Tuple.Create("\"", 9598)
, Tuple.Create(Tuple.Create("", 9568), Tuple.Create<System.Object, System.Int32>(Model.Data.ChangeProviderLink
, 9568), false)
);

WriteLiteral(" aria-label=\"Changing training provider\"");

WriteLiteral(">Change</a>\r\n                        </td>\r\n");

                    }
                    else
                    {

WriteLiteral("                        <td></td>\r\n");

                    }

WriteLiteral("                </tr>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Cohort reference</th>\r\n                    <td>");

                   Write(Model.Data.CohortReference);

WriteLiteral("</td>\r\n                    <td></td>\r\n                </tr>\r\n            </tbody>" +
"\r\n        </table>\r\n\r\n        <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">\r\n            Apprentice details\r\n");

            
             if (Model.Data.EnableEdit)
            {

WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 10214), Tuple.Create("\"", 10256)
, Tuple.Create(Tuple.Create("", 10221), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl("EditApprenticeship")
, 10221), false)
);

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">Edit</a>\r\n");

            }

WriteLiteral("        </h2>\r\n        <table");

WriteLiteral(" class=\"details-list details-list-new\"");

WriteLiteral(">\r\n            <tbody>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Name</th>\r\n                    <td>");

                   Write(Model.Data.FirstName);

WriteLiteral(" ");

                                         Write(Model.Data.LastName);

WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Unique learner number</th>\r\n                    <td>");

                   Write(Model.Data.ULN);

WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Date of birth</th>\r\n                    <td>\r\n");

                        
                         if (Model.Data.DateOfBirth.HasValue)
                        {
                            
                       Write(Model.Data.DateOfBirth.Value.ToGdsFormat());

                                                                       
                        }

WriteLiteral("                    </td>\r\n                </tr>\r\n            </tbody>\r\n        <" +
"/table>\r\n\r\n        <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">\r\n            Apprenticeship details\r\n        </h2>\r\n        <table");

WriteLiteral(" class=\"details-list details-list-new\"");

WriteLiteral(">\r\n            <tbody>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Apprenticeship training course </th>\r\n                    <td>");

                   Write(Model.Data.TrainingName);

WriteLiteral(" </td>\r\n                    <td></td>\r\n                </tr>\r\n                <tr" +
">\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Planned training start date</th>\r\n                    <td>\r\n");

                        
                         if (@Model.Data.StartDate.HasValue)
                        {
                            
                       Write(Model.Data.StartDate.Value.ToGdsFormatWithoutDay());

                                                                               
                        }

WriteLiteral("                    </td>\r\n                    <td></td>\r\n                </tr>\r\n" +
"                <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Planned training finish date</th>\r\n                    <td>\r\n");

                        
                         if (Model.Data.EndDate.HasValue)
                        {
                            
                       Write(Model.Data.EndDate.Value.ToGdsFormatWithoutDay());

                                                                             
                        }

WriteLiteral("                    </td>\r\n                    <td>\r\n");

                        
                         if (Model.Data.PaymentStatus == PaymentStatus.Completed)
                        {

WriteLiteral("                            <a");

WriteLiteral(" id=\"editEndDateLink\"");

WriteAttribute("href", Tuple.Create(" href=\"", 12391), Tuple.Create("\"", 12439)
, Tuple.Create(Tuple.Create("", 12398), Tuple.Create<System.Object, System.Int32>(Model.Data.EditApprenticeshipEndDateLink
, 12398), false)
);

WriteLiteral(" aria-label=\"Edit end date\"");

WriteLiteral(">Edit</a>\r\n");

                        }

WriteLiteral("                    </td>\r\n                </tr>\r\n                <tr>\r\n         " +
"           <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Total agreed apprenticeship price</th>\r\n                    <td>");

                   Write(FormatCost(Model.Data.Cost));

WriteLiteral(" excluding VAT</td>\r\n                    <td></td>\r\n                </tr>\r\n      " +
"          <tr>\r\n                    <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Reference </th>\r\n                    <td>");

                   Write(Model.Data.EmployerReference);

WriteLiteral("</td>\r\n                    <td></td>\r\n                </tr>\r\n");

                
                 if (Model.Data.TrainingType == TrainingType.Standard)
                {

WriteLiteral("                    <tr>\r\n                        <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">End-point assessor</th>\r\n                        <td>");

                        Write(Model.Data.EndpointAssessorName ?? "The end-point assessor has not been declared");

WriteLiteral("</td>\r\n                        <td></td>\r\n                    </tr>\r\n");

                }

WriteLiteral("            </tbody>\r\n        </table>\r\n\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("breadcrumb", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13479), Tuple.Create("\"", 13528)
, Tuple.Create(Tuple.Create("", 13486), Tuple.Create<System.Object, System.Int32>(Model.Data.ManageApprenticeshipV2PageLink
, 13486), false)
);

WriteLiteral(" aria-label=\"Back to manage your apprentices\"");

WriteLiteral(" class=\"back-link\"");

WriteLiteral(">Back to manage your apprentices</a>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

WriteLiteral("\r\n");

DefineSection("gaDataLayer", () => {

WriteLiteral("\r\n    <script>\r\n        sfa.dataLayer.vpv = \'/accounts/apprentices/manage/apprent" +
"ice-details\';\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
