#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerCommitments.Web.Views.EmployerManageApprentices
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.EmployerCommitments;
    using SFA.DAS.EmployerCommitments.Web;
    using SFA.DAS.EmployerCommitments.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmployerManageApprentices/ListAll.cshtml")]
    public partial class ListAll : System.Web.Mvc.WebViewPage<OrchestratorResponse<SFA.DAS.EmployerCommitments.Web.ViewModels.ManageApprenticeships.ManageApprenticeshipsViewModel>>
    {
        public ListAll()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

  
    ViewBag.PageID = "manage-all-apprentices";
    ViewBag.Section = "apprentices";
    ViewBag.Title = "Manage your apprentices";

WriteLiteral("\r\n\r\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Manage your apprentices</h1>\r\n\r\n");

 if (Model.Data.TotalApprenticeshipsBeforeFilter == 0)
{

WriteLiteral("    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column-full\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-border-wide alert-default\"");

WriteLiteral(">\r\n                <p>Once you and your training provider have approved a cohort," +
" the apprentices from that cohort will appear here.</p>\r\n            </div>\r\n   " +
"     </div>\r\n    </div>\r\n");

}
else
{

WriteLiteral("    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column-one-third\"");

WriteLiteral(">\r\n            <!--Search bar-->\r\n            <div");

WriteLiteral(" id=\"search-app\"");

WriteLiteral(">\r\n                <form");

WriteLiteral(" id=\"search-form\"");

WriteLiteral(" method=\"get\"");

WriteAttribute("action", Tuple.Create(" action=\"", 990), Tuple.Create("\"", 1021)
, Tuple.Create(Tuple.Create("", 999), Tuple.Create<System.Object, System.Int32>(Url.Action("ListAll")
, 999), false)
);

WriteLiteral(">\r\n                    <fieldset");

WriteLiteral(" class=\"inline\"");

WriteLiteral(">\r\n                        <legend><h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Search for an apprentice</h2></legend>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"search-input\"");

WriteLiteral(" name=\"SearchInput\"");

WriteLiteral(" class=\"search-text form-control\"");

WriteLiteral(" data-default-value=\"");

                                                                                                                                Write(Model.Data.SearchInputPlaceholder);

WriteLiteral("\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1339), Tuple.Create("\"", 1378)
                                                                                                , Tuple.Create(Tuple.Create("", 1347), Tuple.Create<System.Object, System.Int32>(Model.Data.Filters.SearchInput
, 1347), false)
);

WriteLiteral(" />\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"submit-search form-control\"");

WriteLiteral(" />\r\n                        <input");

WriteLiteral(" name=\"ResetFilter\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"True\"");

WriteLiteral(">\r\n                    </fieldset>\r\n                </form>\r\n            </div>\r\n" +
"            <hr");

WriteLiteral(" class=\"black\"");

WriteLiteral(" />\r\n            <h2");

WriteLiteral(" class=\"heading-medium filter-app-head\"");

WriteLiteral(">Filter apprentices</h2>\r\n\r\n            <form");

WriteLiteral(" method=\"GET\"");

WriteAttribute("action", Tuple.Create(" action=\"", 1771), Tuple.Create("\"", 1802)
, Tuple.Create(Tuple.Create("", 1780), Tuple.Create<System.Object, System.Int32>(Url.Action("ListAll")
, 1780), false)
);

WriteLiteral(" novalidate=\"novalidate\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

           Write(Html.Partial("ApprenticeshipFilters", Model.Data.Filters));

WriteLiteral("\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(" value=\"Filter\"");

WriteLiteral(" id=\"submit-app-filter\"");

WriteLiteral(">Filter apprentices</button>\r\n                <p>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2069), Tuple.Create("\"", 2098)
, Tuple.Create(Tuple.Create("", 2076), Tuple.Create<System.Object, System.Int32>(Url.Action("ListAll")
, 2076), false)
);

WriteLiteral(" title=\"Reset\"");

WriteLiteral(" class=\"button text-link reset-link\"");

WriteLiteral(">Reset</a>\r\n                </p>\r\n");

WriteLiteral("                ");

           Write(Html.Hidden("SearchInput", Model.Data.Filters.SearchInput));

WriteLiteral("\r\n                <input");

WriteLiteral(" name=\"ResetFilter\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"False\"");

WriteLiteral(">\r\n            </form>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n\r\n");

            
             if (Model.Data.TotalResults == 0)
            {

WriteLiteral("                <div");

WriteLiteral(" id=\"no-search-results\"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">No results found.</h3>\r\n                    <p>\r\n                        You can" +
" search again or <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2668), Tuple.Create("\"", 2697)
, Tuple.Create(Tuple.Create("", 2675), Tuple.Create<System.Object, System.Int32>(Url.Action("ListAll")
, 2675), false)
);

WriteLiteral(" title=\"see all apprentices\"");

WriteLiteral(" class=\"text-link\"");

WriteLiteral(">see all apprentices</a>\r\n                    </p>\r\n                </div>\r\n");

            }
            else
            {

WriteLiteral("                <div");

WriteLiteral(" id=\"total-count\"");

WriteLiteral(">\r\n                    <p>\r\n                        <strong>");

                           Write(Model.Data.TotalResults);

WriteLiteral("</strong> record");

                                                                    Write(Model.Data.TotalResults > 1 ? "s" : null);

WriteLiteral(" found.\r\n                    </p>\r\n                    <p>\r\n                     " +
"   You can search again or <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3158), Tuple.Create("\"", 3187)
, Tuple.Create(Tuple.Create("", 3165), Tuple.Create<System.Object, System.Int32>(Url.Action("ListAll")
, 3165), false)
);

WriteLiteral(" title=\"see all apprentices\"");

WriteLiteral(" class=\"text-link\"");

WriteLiteral(">see all apprentices</a>\r\n                    </p>\r\n                </div>\r\n");

WriteLiteral("                <table");

WriteLiteral(" class=\"tableResponsive\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Unique learner number</th>
                            <th>Date of birth</th>
                            <th>Status</th>
                            <th>Alerts</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
");

                        
                         foreach (var apprenticeship in Model.Data.Apprenticeships)
                        {

WriteLiteral("                            <tr>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

                               Write(apprenticeship.FirstName);

WriteLiteral(" ");

                                                         Write(apprenticeship.LastName);

WriteLiteral(" &nbsp;\r\n                                </td>\r\n                                <" +
"td");

WriteLiteral(" id=\"apprenticeUln\"");

WriteLiteral(">");

                                                  Write(apprenticeship.ULN);

WriteLiteral("</td>\r\n                                <td>\r\n");

                                    
                                     if (apprenticeship.DateOfBirth.HasValue)
                                    {
                                        
                                   Write(apprenticeship.DateOfBirth.Value.ToGdsFormat());

                                                                                       
                                    }
WriteLiteral(" &nbsp;\r\n                                </td>\r\n                                <" +
"td>\r\n");

WriteLiteral("                                    ");

                               Write(apprenticeship.Status);

WriteLiteral(" &nbsp;\r\n                                </td>\r\n                                <" +
"td>\r\n");

                                    
                                     foreach (var a in apprenticeship.Alerts)
                                    {

WriteLiteral("                                        <div>\r\n");

WriteLiteral("                                            ");

                                       Write(a);

WriteLiteral("\r\n                                        </div>\r\n");

                                    }

WriteLiteral("                                </td>\r\n                                <td>\r\n    " +
"                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5118), Tuple.Create("\"", 5245)
, Tuple.Create(Tuple.Create("", 5125), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", new {Model.Data.HashedAccountId, hashedApprenticeshipId = apprenticeship.HashedApprenticeshipId})
, 5125), false)
);

WriteAttribute("title", Tuple.Create("\r\n                                       title=\"", 5246), Tuple.Create("\"", 5350)
, Tuple.Create(Tuple.Create("", 5294), Tuple.Create("View", 5294), true)
, Tuple.Create(Tuple.Create("  ", 5298), Tuple.Create<System.Object, System.Int32>(apprenticeship.FirstName
, 5300), false)
, Tuple.Create(Tuple.Create(" ", 5325), Tuple.Create<System.Object, System.Int32>(apprenticeship.LastName
, 5326), false)
);

WriteAttribute("aria-label", Tuple.Create("\r\n                                       aria-label=\"", 5351), Tuple.Create("\"", 5459)
, Tuple.Create(Tuple.Create("", 5404), Tuple.Create("View", 5404), true)
, Tuple.Create(Tuple.Create(" ", 5408), Tuple.Create<System.Object, System.Int32>(apprenticeship.FirstName
, 5409), false)
 , Tuple.Create(Tuple.Create(" ", 5434), Tuple.Create<System.Object, System.Int32>(apprenticeship.LastName
, 5435), false)
);

WriteLiteral(">View</a>\r\n                                </td>\r\n                            </t" +
"r>\r\n");

                        }

WriteLiteral("                    </tbody>\r\n                </table>\r\n");


                    
               Write(Html.Partial("Pagination", Model.Data));

                                                           
            }

WriteLiteral("        </div>\r\n    </div>\r\n");

}

WriteLiteral("\r\n");

DefineSection("breadcrumb", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5803), Tuple.Create("\"", 5853)
, Tuple.Create(Tuple.Create("", 5810), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "EmployerCommitments")
, 5810), false)
);

WriteLiteral(" aria-label=\"Back to apprentices\"");

WriteLiteral(" class=\"back-link\"");

WriteLiteral(">Back to apprentices</a>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

DefineSection("gaDataLayer", () => {

WriteLiteral("\r\n    <script>\r\n        sfa.dataLayer.vpv = \'/accounts/apprentices/manage/list-al" +
"l-apprentices\';\r\n        sfa.dataLayer.statuses = \'");

                             Write(Model.Data.Filters.Status.Count);

WriteLiteral("\';\r\n        sfa.dataLayer.alerts = \'");

                           Write(Model.Data.Filters.RecordStatus.Count);

WriteLiteral("\';\r\n        sfa.dataLayer.courses = \'");

                            Write(Model.Data.Filters.Course.Count);

WriteLiteral("\';\r\n        sfa.dataLayer.providers = \'");

                              Write(Model.Data.Filters.Provider.Count);

WriteLiteral("\';\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
