#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerCommitments.Web.Views.EmployerManageApprentices
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.EmployerCommitments;
    using SFA.DAS.EmployerCommitments.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmployerManageApprentices/ViewChanges.cshtml")]
    public partial class ViewChanges : System.Web.Mvc.WebViewPage<SFA.DAS.EmployerCommitments.Web.OrchestratorResponse<SFA.DAS.EmployerCommitments.Web.ViewModels.ManageApprenticeships.UpdateApprenticeshipViewModel>>
    {
        public ViewChanges()
        {
        }
        public override void Execute()
        {
  
    ViewBag.Title = "View changes";
    ViewBag.PageID = "view-changes";
    ViewBag.Section = "apprentices";

    Model.Data.CurrentTableHeadingText = "Previous";

    var learnerName = $"{Model.Data?.OriginalApprenticeship?.FirstName} {Model.Data?.OriginalApprenticeship?.LastName}";
    var uln = Model.Data?.OriginalApprenticeship?.ULN;
    var trainingName = Model.Data?.OriginalApprenticeship?.TrainingName;

WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" method=\"POST\"");

WriteAttribute("action", Tuple.Create(" action=\"", 730), Tuple.Create("\"", 765)
, Tuple.Create(Tuple.Create("", 739), Tuple.Create<System.Object, System.Int32>(Url.Action("ViewChanges")
, 739), false)
);

WriteLiteral(" novalidate=\"novalidate\"");

WriteAttribute("onsubmit", Tuple.Create(" onsubmit=\"", 790), Tuple.Create("\"", 848)
, Tuple.Create(Tuple.Create("", 801), Tuple.Create("sfa.tagHelper.submitRadioForm(\'", 801), true)
                                                  , Tuple.Create(Tuple.Create("", 832), Tuple.Create<System.Object, System.Int32>(ViewBag.Title
, 832), false)
, Tuple.Create(Tuple.Create("", 846), Tuple.Create("\')", 846), true)
);

WriteLiteral(">\r\n\r\n");

WriteLiteral("            ");

       Write(Html.AntiForgeryToken());

WriteLiteral("\r\n\r\n            <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">");

                                  Write(ViewBag.Title);

WriteLiteral("</h1>\r\n            \r\n");

            
               Html.RenderPartial("_CoreDetail", new CoreDetailsViewModel
                {
                    LearnerName = learnerName,
                    ULN = uln,
                    TrainingName = trainingName
                }); 
WriteLiteral("\r\n\r\n            <p");

WriteLiteral(" class=\"lede\"");

WriteLiteral(">");

                       Write(Model.Data.ProviderName);

WriteLiteral(" are reviewing these changes:</p>\r\n");

WriteLiteral("            ");

       Write(Html.Partial("ApprenticeshipUpdate", Model.Data));

WriteLiteral("\r\n\r\n            <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Do you want to undo these changes?</h2>\r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1464), Tuple.Create("\"", 1556)
, Tuple.Create(Tuple.Create("", 1472), Tuple.Create("form-group", 1472), true)
, Tuple.Create(Tuple.Create(" ", 1482), Tuple.Create<System.Object, System.Int32>(!string.IsNullOrEmpty(Model.Data.ChangesConfirmedError) ? "error" : ""
, 1483), false)
);

WriteLiteral(">\r\n                <fieldset>\r\n                    <legend");

WriteLiteral(" class=\"visually-hidden\"");

WriteLiteral(">Do you want to undo these changes?</legend>\r\n\r\n                    <div");

WriteLiteral(" id=\"ChangesConfirmed\"");

WriteLiteral("></div>\r\n");

                    
                     if (!string.IsNullOrEmpty(Model.Data.ChangesConfirmedError))
                    {

WriteLiteral("                        <span");

WriteLiteral(" class=\"error-message\"");

WriteLiteral(" id=\"error-message-ChangesConfirmed\"");

WriteLiteral(">");

                                                                                   Write(Model.Data.ChangesConfirmedError);

WriteLiteral("</span>\r\n");

                    }

WriteLiteral("\r\n                    <label");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(" for=\"changes-undo-true\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

                   Write(Html.RadioButton("ChangesConfirmed", true, new { id = "changes-undo-true", dataOptionName = "Yes", onclick = $"sfa.tagHelper.radioButtonClick('{ViewBag.Title}', 'Yes')" }));

WriteLiteral("\r\n                        Yes, undo these changes\r\n                    </label>\r\n" +
"                    <label");

WriteLiteral(" class=\"block-label selection-button-radio\"");

WriteLiteral(" for=\"changes-undo-false\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

                   Write(Html.RadioButton("ChangesConfirmed", false, new { id = "changes-undo-false", dataOptionName = "No", onclick = $"sfa.tagHelper.radioButtonClick('{ViewBag.Title}', 'No')" }));

WriteLiteral("\r\n                        No, keep these changes\r\n                    </label>\r\n " +
"               </fieldset>\r\n            </div>\r\n\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(" aria-label=\"Continue\"");

WriteLiteral(" id=\"submit-view-changes\"");

WriteLiteral(">Continue</button>\r\n        </form>\r\n\r\n    </div>\r\n</div>\r\n\r\n\r\n");

DefineSection("breadcrumb", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3022), Tuple.Create("\"", 3151)
, Tuple.Create(Tuple.Create("", 3029), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", "EmployerManageApprentices", new { Model.Data.HashedAccountId, Model.Data.HashedApprenticeshipId} )
, 3029), false)
);

WriteLiteral(" aria-label=\"Back to apprentice details\"");

WriteLiteral(" class=\"back-link\"");

WriteLiteral(">Back to apprentice details</a>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

DefineSection("gaDataLayer", () => {

WriteLiteral("\r\n    <script>\r\n        sfa.dataLayer.vpv = \'/accounts/apprentices/manage/view-ch" +
"anges\';\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
