#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerCommitments.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.EmployerCommitments;
    using SFA.DAS.EmployerCommitments.Web.Extensions;
    using SFA.DAS.EmployerCommitments.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CoreDetail.cshtml")]
    public partial class CoreDetail : System.Web.Mvc.WebViewPage<CoreDetailsViewModel>
    {
        public CoreDetail()
        {
        }
        public override void Execute()
        {
WriteLiteral("<table");

WriteLiteral(" class=\"core-detail\"");

WriteLiteral(">\r\n    <tr>\r\n        <td");

WriteLiteral(" class=\"first-child\"");

WriteLiteral(">Name</td>\r\n        <td");

WriteLiteral(" id=\"learnerName\"");

WriteLiteral(" class=\"first-child\"");

WriteLiteral(">");

                                            Write(Model.LearnerName);

WriteLiteral("</td>\r\n    </tr>\r\n    <tr>\r\n        <td");

WriteLiteral(" class=\"first-child\"");

WriteLiteral(">Unique learner number</td>\r\n        <td");

WriteLiteral(" id=\"uln\"");

WriteLiteral(" class=\"first-child\"");

WriteLiteral(">");

                                    Write(Model.ULN);

WriteLiteral("</td>\r\n    </tr>\r\n    <tr>\r\n        <td");

WriteLiteral(" class=\"first-child\"");

WriteLiteral(">Training name</td>\r\n        <td");

WriteLiteral(" id=\"trainingName\"");

WriteLiteral(" class=\"first-child\"");

WriteLiteral(">");

                                             Write(Model.TrainingName);

WriteLiteral("</td>\r\n    </tr>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
