#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerCommitments.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.DAS.EmployerCommitments;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/ApprenticeshipFilters.cshtml")]
    public partial class ApprenticeshipFilters : System.Web.Mvc.WebViewPage<SFA.DAS.EmployerCommitments.Web.ViewModels.ManageApprenticeships.ApprenticeshipFiltersViewModel>
    {
 
    private static HtmlString RenderFilterOptions(string groupName, List<KeyValuePair<string, string>> options, List<string> selected)
    {
        var result = new StringBuilder();

        foreach (var option in options)
        {
            var checkedAtt = selected != null && selected.Contains(option.Key) ? "checked=\"checked\"" : "";
            result.Append("<div class=\"item\">");
            result.Append($"<label for= \"{groupName}-{option.Key}\">");
            result.Append($"<input name=\"{groupName}\" value =\"{option.Key}\" class=\"js-option-select\" id =\"{groupName}-{option.Key}\" type = \"checkbox\" {checkedAtt} aria-controls=\"js-search-results-info\">");
            result.Append($"<span>{option.Value}</span>");
            result.Append("</label>");
            result.Append("</div>");
        }

        return new HtmlString(result.ToString());
    }

        public ApprenticeshipFilters()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"filter-option-select\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-head js-container-head\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"option-select-label\"");

WriteLiteral(">Status</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"options-container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(RenderFilterOptions("Status", Model.ApprenticeshipStatusOptions, Model.Status));

WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"filter-option-select\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-head js-container-head\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"option-select-label\"");

WriteLiteral(">Alerts</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"options-container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(RenderFilterOptions("RecordStatus", Model.RecordStatusOptions, Model.RecordStatus));

WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"filter-option-select\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-head js-container-head\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"option-select-label\"");

WriteLiteral(">Training Courses</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"options-container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(RenderFilterOptions("Course", Model.TrainingCourseOptions, Model.Course));

WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"filter-option-select\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-head js-container-head\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"option-select-label\"");

WriteLiteral(">Provider</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"options-container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(RenderFilterOptions("Provider", Model.ProviderOrganisationOptions, Model.Provider));

WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"filter-option-select\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-head js-container-head\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"option-select-label\"");

WriteLiteral(">Funding Status</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"options-container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(RenderFilterOptions("FundingStatus", Model.FundingStatusOptions, Model.FundingStatus));

WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
